1.	name: gentong
2.	 
3.	on: workflow_dispatch 
4.	 
5.	jobs: 
6.	 
7.	build: 
8.	 
9.	runs-on: windows-latest 
10.	 
11.	timeout-minutes: 9999 
12.	 
13.	steps: 
14.	 
15.	- name: Download Ngrok. 
16.	 
17.	run: | 
18.	Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip 
19.	Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/start.bat -OutFile start.bat 
20.	Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/wallpaper.bat -OutFile wallpaper.bat 
21.	Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/loop.bat -OutFile loop.bat 
22.	Invoke-WebRequest https://raw.githubusercontent.com/Zakybotz/Rdp-Free/master/start.bat -OutFile push.bat 
23.	- name: Extract Ngrok File. 
24.	 
25.	run: Expand-Archive ngrok.zip 
26.	 
27.	- name: Connect Ngrok. 
28.	 
29.	run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN 
30.	 
31.	env: 
32.	 
33.	NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }} 
34.	 
35.	- name: Windows10 RDP. 
36.	 
37.	run: | 
38.	Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0 
39.	Enable-NetFirewallRule -DisplayGroup "Remote Desktop" 
40.	Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1 
41.	copy wallpaper.bat D:\a\wallpaper.bat 
42.	- name: Tunnel. 
43.	 
44.	run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"' 
45.	 
46.	- name: Connect RDP. 
47.	 
48.	run: cmd /c start.bat 
49.	 
50.	- name: win10 RDP. 
51.	 
52.	run: cmd /c loop.bat

